databases:
  - name: sa19-act2-db
    plan: free

services:
  - type: web
    name: sa19-act2-app
    runtime: ruby
    plan: free
    region: oregon
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -p $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sa19-act2-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
